### ISSUE TITLE
доработать систему апгрейдов

### ISSUE THREAD

**Issue by perk3greed** [perk3greed/bo2#6]
как должны выглядеть апгрейды в своей следующей итерации: 
- при выборе апгрейда тратятся очки которые есть у игрока (var player_money в Events.gd)
- после выбора апгрейдов для показывания они возвращаются в свой массив апгрейдов (сейчас после выбора они удаляются и после двух шафлов там ничего не остается). Повторяю - сейчас при показе удаляется не только апгрейд который выбран, но и те которые не выбраны 
- сделать, что бы при отсутствии достаточного количества апгрейдов они просто не показывались, а не крашились с ошибкой
- разделить апгрейды на 3 категории - ютилити, общие и оружие
- разнести стоимость, название и картинку, описание сделать меньше, их переместить на место описания
- добавить большую кнопку пропуска апгрейдов, при ее нажатии окно апгрейдов закрывается (как в хсе по размеру, что бы видно было, где то снизу окна апгрейдов)

**Comment by marivan-hub** [comment]
a'dasd

**Comment by marivan-hub** [comment]
последний апгрейд остается навсегда

**Comment by marivan-hub** [comment]
- [x] при выборе апгрейда тратятся очки которые есть у игрока (var player_money в Events.gd) 
- [x] после выбора апгрейдов для показывания они возвращаются в свой массив апгрейдов (сейчас после выбора они удаляются и после двух шафлов там ничего не остается). Повторяю - сейчас при показе удаляется не только апгрейд который выбран, но и те которые не выбраны
- [x] сделать, что бы при отсутствии достаточного количества апгрейдов они просто не показывались, а не крашились с ошибкой
- [x] разделить апгрейды на 3 категории - ютилити, общие и оружие
- [x] разнести стоимость, название и картинку, описание сделать меньше, их переместить на место описания
- [x] добавить большую кнопку пропуска апгрейдов, при ее нажатии окно апгрейдов закрывается (как в хсе по размеру, что бы видно было, где то снизу окна апгрейдов)
